### PR TITLE
Trying for second time

### PR DESCRIPTION
**Pull request by soheilzh**

### CODE REVIEW

**Comment by fedhere** [comment]
you had opened and closed a pull request. I reopened it and merged it. let
me know if that is not what you wanted to merge

On Thu, Dec 17, 2015 at 4:14 AM, soheilzh notifications@github.com wrote:

> Closed #32 https://github.com/fedhere/PUI2015_EC/pull/32.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fedhere/PUI2015_EC/pull/32#event-494461194.

## 

---

dr. federica bianco
James Arthur Fellow
NYU-Center for Cosmology & Particle Physics
NYU-Center for Urban Science & Progress
New York, NY

http://cosmo.nyu.edu/~fb55/

---

  //\
 //||\     Please consider the environment before printing this e-mail

email checking schedule:
9-5 on the hour. otherwise sporadically.

**Comment by soheilzh** [comment]
Hi Federica,
I am just not sure how to deliver you my big data file(~130MB). I didn't
upload it to git due to its big size and forgot to modify how I read it in
my notebook(for reproducibility).
Thank you very much.
​
 311_Service_Requests_from_01_2015_to_Present.csv
http://s.bl-1.com/h/vfDLdzd?url=https://drive.google.com/file/d/0B39tXUskshibTDE3bzl1Yk02WEU/view?usp=drive_web
​

On Thu, Dec 17, 2015 at 10:16 AM, federica notifications@github.com wrote:

> you had opened and closed a pull request. I reopened it and merged it. let
> me know if that is not what you wanted to merge
> 
> On Thu, Dec 17, 2015 at 4:14 AM, soheilzh notifications@github.com
> wrote:
> 
> > Closed #32 https://github.com/fedhere/PUI2015_EC/pull/32.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/fedhere/PUI2015_EC/pull/32#event-494461194.
> 
> ## 
> 
> ---
> 
> dr. federica bianco
> James Arthur Fellow
> NYU-Center for Cosmology & Particle Physics
> NYU-Center for Urban Science & Progress
> New York, NY
> 
> http://cosmo.nyu.edu/~fb55/
> 
> ---
> 
> //\
> //||\ Please consider the environment before printing this e-mail
> 
> email checking schedule:
> 9-5 on the hour. otherwise sporadically.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fedhere/PUI2015_EC/pull/32#issuecomment-165480552.

## 

Soheil Zhalehpour

**Comment by fedhere** [comment]
It's just the 311 data pulled from the NYC data portal right? If it's that
don't worry, I have it.

On Thursday, December 17, 2015, soheilzh notifications@github.com wrote:

> Hi Federica,
> I am just not sure how to deliver you my big data file(~130MB). I didn't
> upload it to git due to its big size and forgot to modify how I read it in
> my notebook(for reproducibility).
> Thank you very much.
> ​
> 311_Service_Requests_from_01_2015_to_Present.csv
> <
> http://s.bl-1.com/h/vfDLdzd?url=https://drive.google.com/file/d/0B39tXUskshibTDE3bzl1Yk02WEU/view?usp=drive_web
> 
> > ​
> 
> On Thu, Dec 17, 2015 at 10:16 AM, federica <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > you had opened and closed a pull request. I reopened it and merged it.
> > let
> > me know if that is not what you wanted to merge
> > 
> > On Thu, Dec 17, 2015 at 4:14 AM, soheilzh <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > Closed #32 https://github.com/fedhere/PUI2015_EC/pull/32.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/fedhere/PUI2015_EC/pull/32#event-494461194.
> > 
> > ## 
> > 
> > ---
> > 
> > dr. federica bianco
> > James Arthur Fellow
> > NYU-Center for Cosmology & Particle Physics
> > NYU-Center for Urban Science & Progress
> > New York, NY
> > 
> > http://cosmo.nyu.edu/~fb55/
> > 
> > ---
> > 
> > //\
> > //||\ Please consider the environment before printing this e-mail
> > 
> > email checking schedule:
> > 9-5 on the hour. otherwise sporadically.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/fedhere/PUI2015_EC/pull/32#issuecomment-165480552.
> 
> ## 
> 
> Soheil Zhalehpour
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fedhere/PUI2015_EC/pull/32#issuecomment-165519820.

## 

 /|/\
   |\*  Please consider the environment before printing this e-mail

**Comment by soheilzh** [comment]
yes but only for year 2015. Thank you.

On Thu, Dec 17, 2015 at 1:53 PM, federica notifications@github.com wrote:

> It's just the 311 data pulled from the NYC data portal right? If it's that
> don't worry, I have it.
> 
> On Thursday, December 17, 2015, soheilzh notifications@github.com wrote:
> 
> > Hi Federica,
> > I am just not sure how to deliver you my big data file(~130MB). I didn't
> > upload it to git due to its big size and forgot to modify how I read it
> > in
> > my notebook(for reproducibility).
> > Thank you very much.
> > ​
> > 311_Service_Requests_from_01_2015_to_Present.csv
> > <
> > 
> > http://s.bl-1.com/h/vfDLdzd?url=https://drive.google.com/file/d/0B39tXUskshibTDE3bzl1Yk02WEU/view?usp=drive_web
> > 
> > > ​
> > 
> > On Thu, Dec 17, 2015 at 10:16 AM, federica <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > 
> > > you had opened and closed a pull request. I reopened it and merged it.
> > > let
> > > me know if that is not what you wanted to merge
> > > 
> > > On Thu, Dec 17, 2015 at 4:14 AM, soheilzh <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > wrote:
> > > 
> > > > Closed #32 https://github.com/fedhere/PUI2015_EC/pull/32.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/fedhere/PUI2015_EC/pull/32#event-494461194.
> > > 
> > > ## 
> > > 
> > > ---
> > > 
> > > dr. federica bianco
> > > James Arthur Fellow
> > > NYU-Center for Cosmology & Particle Physics
> > > NYU-Center for Urban Science & Progress
> > > New York, NY
> > > 
> > > http://cosmo.nyu.edu/~fb55/
> > > 
> > > ---
> > > 
> > > //\
> > > //||\ Please consider the environment before printing this e-mail
> > > 
> > > email checking schedule:
> > > 9-5 on the hour. otherwise sporadically.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/fedhere/PUI2015_EC/pull/32#issuecomment-165480552
> > > .
> > 
> > ## 
> > 
> > Soheil Zhalehpour
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/fedhere/PUI2015_EC/pull/32#issuecomment-165519820.
> 
> ## 
> 
> /|/\
> |\* Please consider the environment before printing this e-mail
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fedhere/PUI2015_EC/pull/32#issuecomment-165546742.

## 

Soheil Zhalehpour

**Pull request merged**
